// might change, the messages are generated by copilot

export const motivationalMessages = [
    "There's code waiting to be written, fire up your editor and bring your next project to life!",
    // "There's a new challenge waiting in your codebase. Re-engage with your project and solve your next programming puzzle!",
    "Your next innovative feature could start today. Open your editor and keep hacking!",
    "Your next big idea is only a commit away. Return to your project and keep building something great!",
    "There's always another bug to squash or feature to build. Jump back into your codebase and keep hacking!",
    "Every software milestone starts with a single commit. Begin coding and move your project forward!",
    "Dive into your favorite language and explore new libraries or frameworks to expand your toolkit!",
    // "From fixing typos to implementing complex features, all progress matters. Make your mark in code today!",
    "There's always room to optimize or enhance your code!",
    "Your next successful deployment could start with a single commit!",
    // "Debugging and refining code are essential parts of the developer experience. Take some time today to polish your work!",
    "Take some time today to polish your work!",
    "Every improvement, from UI tweaks to backend refactors, is a step toward better software!",
    "Take this opportunity to implement that feature you've been considering. Time spent hacking always pays off!",
    "Don't let unfinished ideas fade away, return to your drafts and bring them to life!",
    // "Build something fun, like a game or creative tool, to keep your hacking sessions engaging!",
    "Let curiosity guide your next session, explore new APIs, SDKs, or cloud services in your code!",
    "Today is the perfect time to implement that algorithm you've been thinking about!",
    "Hack together a quick prototype, and see how your ideas take shape in code!",
    "Return to your backlog and pick a task that challenges your current skills!",
    "Refactor a piece of code to improve its readability or performance!",
    "Optimize your development environment for better productivity and efficiency!",
    "Strengthen your debugging skills by tracking down and fixing a persistent error in your project!",

]