package com.stefdp.hackatime.network.models

import com.google.gson.annotations.SerializedName

data class Heartbeat(
    val id: Long,
    @SerializedName("user_id") val userId: Long,
    val branch: String,
    val category: String,
    val dependencies: List<Any> = emptyList(),
    val editor: String,
    val entity: String,
    val language: String,
    val machine: String,
    @SerializedName("operating_system") val operatingSystem: String,
    val project: String,
    val type: String,
    @SerializedName("user_agent") val userAgent: String,
    @SerializedName("line_additions") val lineAdditions: Int?,
    @SerializedName("line_deletions") val lineDeletions: Int?,
    val lineno: Int,
    val cursorpos: Int,
    @SerializedName("project_root_count") val projectRootCount: Int,
    val time: Int,
    @SerializedName("is_write") val isWrite: Boolean?,
    @SerializedName("created_at") val createdAt: String,
    @SerializedName("updated_at") val updatedAt: String,
    @SerializedName("fields_hash") val fieldsHash: String,
    @SerializedName("source_type") val sourceType: String,
    @SerializedName("ip_address") val ipAddress: String,
    @SerializedName("ysws_program") val yswsProgram: String,
    @SerializedName("deleted_at") val deletedAt: String?,
    @SerializedName("raw_data") val rawData: HeartbeatRawData,
    @SerializedName("raw_heartbeat_upload_id") val rawHeartbeatUploadId: Long
)

data class HeartbeatRawData(
    val time: Int,
    val type: String,
    val lines: Int,
    val branch: String,
    val eidtor: String,
    val entity: String,
    val lineno: Int,
    val machine: String,
    val project: String,
    @SerializedName("user_id") val userId: Long,
    val category: String,
    @SerializedName("is_write") val isWrite: Boolean?,
    val cursorpos: Int,
    @SerializedName("user_agent") val userAgent: String,
    val dependencies: List<Any> = emptyList(),
    @SerializedName("line_additions") val lineAdditions: Int?,
    @SerializedName("line_deletions") val lineDeletions: Int?,
    @SerializedName("operating_system") val operatingSystem: String,
    @SerializedName("project_root_count") val projectRootCount: Int,
)